"""Football-specific Growth adapters and candidate builders.

ROSClaw Core owns task-neutral evidence and safety contracts.  This package
owns the football semantics that populate those contracts.  Importing it has
no simulator, runtime, ROS, or hardware side effects.
"""

from rosclaw_soccer.growth.adapter import SOCCER_GROWTH_ADAPTER, SoccerGrowthAdapter
from rosclaw_soccer.growth.alternating_team_growth import (
    AlternatingGrowthDecision,
    AlternatingGrowthGateConfig,
    AlternatingGrowthRoundDecision,
    AlternatingTeamEpisode,
    CurriculumCell,
    FailureMemoryRecord,
    GrowthPartition,
    PhaseScore,
    RoleGenerationBinding,
    TeamFailureCode,
    TeamSkillPhase,
    build_failure_conditioned_dreams,
    evaluate_alternating_growth,
    evaluate_alternating_growth_round,
    prioritize_team_curriculum,
)
from rosclaw_soccer.growth.canonical_champion import (
    SoccerChampionEvidenceLayout,
    reconstruct_s33_champion_registry,
    write_s33_champion_registry,
)
from rosclaw_soccer.growth.dynamic_lead_pass import (
    DynamicLeadPassPolicy,
    LeadPassCalibrationSample,
    fit_dynamic_lead_pass_policy,
)
from rosclaw_soccer.growth.first_touch import (
    FirstTouchEvaluation,
    FirstTouchFailure,
    FirstTouchGateConfig,
    FirstTouchMeasurement,
    build_first_touch_dream,
    evaluate_first_touch,
)
from rosclaw_soccer.growth.independent_agent_cell import (
    AgentCellDecision,
    AgentCellObservation,
    AgentPhysicalState,
    AgentTacticalProfile,
    RosclawSoccerAgentCell,
    build_agent_plasticity_lease,
    build_independent_agent_cell,
    build_team_coordination_frame,
)
from rosclaw_soccer.growth.joint_policy_search import (
    JointPolicySearchConfig,
    JointPolicySearchDecision,
    MirroredRoleProbe,
    RolePolicySearchSpace,
    RolePolicySearchUpdate,
    RolePolicyVector,
    default_three_role_search_spaces,
    learn_joint_policy_generation,
)
from rosclaw_soccer.growth.mjlab_getup import (
    MJLabGetUpContract,
    MJLabGetUpTorchController,
    MJLabRecoveryHandoff,
    MJLabRecoveryHandoffConfig,
    MJLabRecoveryHandoffSignals,
    load_mjlab_getup_torch,
)
from rosclaw_soccer.growth.mosaic_getup import (
    G1MosaicGMTGetUpSkill,
    build_g1_mosaic_gmt_getup_skill,
    load_g1_mosaic_gmt_getup_skill,
)
from rosclaw_soccer.growth.mosaic_gmt import (
    G1MosaicGMTOverheadSkill,
    MosaicGMTContract,
    MosaicGMTTorchController,
    build_g1_mosaic_gmt_overhead_skill,
    load_g1_mosaic_gmt_overhead_skill,
    load_mosaic_gmt_torch,
)
from rosclaw_soccer.growth.paired_champion_gate import (
    ChampionMetricSpec,
    ChampionSnapshot,
    PairedChampionDecision,
    decision_payload,
    evaluate_paired_champion,
)
from rosclaw_soccer.growth.physical_option_router import (
    PhysicalOptionOutcome,
    PhysicalOptionRequest,
    PhysicalOptionTerminal,
    PhysicalSoccerOption,
    build_physical_option_request,
)
from rosclaw_soccer.growth.role_learning import (
    JointGrowthDecision,
    JointGrowthGateConfig,
    JointGrowthRoundDecision,
    RoleEpisodeOutcome,
    RoleGrowthMetrics,
    RolePolicyBinding,
    SharedWorldTeamEpisode,
    SoccerRole,
    SoccerSide,
    evaluate_joint_growth,
    evaluate_joint_growth_round,
)
from rosclaw_soccer.growth.tactical_2v1 import (
    MatchedTacticalRollout,
    TacticalAction,
    TacticalRewardWeights,
    TwoVsOneDecisionEvidence,
    TwoVsOneState,
)
from rosclaw_soccer.growth.tactical_2v1_actor import (
    TwoVsOneTacticalActor,
    TwoVsOneTacticalDecision,
    fit_two_vs_one_tactical_actor,
    load_two_vs_one_tactical_actor,
    save_two_vs_one_tactical_actor,
)
from rosclaw_soccer.growth.upper_corner_strike import (
    UpperCornerLaneAction,
    UpperCornerStrikePolicy,
)

__all__ = [
    "AlternatingGrowthDecision",
    "AlternatingGrowthGateConfig",
    "AlternatingGrowthRoundDecision",
    "AlternatingTeamEpisode",
    "AgentCellDecision",
    "AgentCellObservation",
    "AgentPhysicalState",
    "AgentTacticalProfile",
    "CurriculumCell",
    "DynamicLeadPassPolicy",
    "FailureMemoryRecord",
    "FirstTouchEvaluation",
    "FirstTouchFailure",
    "FirstTouchGateConfig",
    "FirstTouchMeasurement",
    "GrowthPartition",
    "JointGrowthDecision",
    "JointGrowthGateConfig",
    "JointGrowthRoundDecision",
    "JointPolicySearchConfig",
    "JointPolicySearchDecision",
    "LeadPassCalibrationSample",
    "G1MosaicGMTGetUpSkill",
    "G1MosaicGMTOverheadSkill",
    "ChampionMetricSpec",
    "ChampionSnapshot",
    "MirroredRoleProbe",
    "MJLabGetUpContract",
    "MJLabGetUpTorchController",
    "MJLabRecoveryHandoff",
    "MJLabRecoveryHandoffConfig",
    "MJLabRecoveryHandoffSignals",
    "MatchedTacticalRollout",
    "MosaicGMTContract",
    "MosaicGMTTorchController",
    "PairedChampionDecision",
    "PhaseScore",
    "PhysicalOptionOutcome",
    "PhysicalOptionRequest",
    "PhysicalOptionTerminal",
    "PhysicalSoccerOption",
    "RoleEpisodeOutcome",
    "RoleGrowthMetrics",
    "RolePolicySearchSpace",
    "RolePolicySearchUpdate",
    "RolePolicyBinding",
    "RolePolicyVector",
    "RoleGenerationBinding",
    "RosclawSoccerAgentCell",
    "SOCCER_GROWTH_ADAPTER",
    "SharedWorldTeamEpisode",
    "SoccerGrowthAdapter",
    "SoccerChampionEvidenceLayout",
    "SoccerRole",
    "SoccerSide",
    "TacticalAction",
    "TacticalRewardWeights",
    "TeamFailureCode",
    "TeamSkillPhase",
    "UpperCornerLaneAction",
    "UpperCornerStrikePolicy",
    "TwoVsOneDecisionEvidence",
    "TwoVsOneState",
    "TwoVsOneTacticalActor",
    "TwoVsOneTacticalDecision",
    "build_first_touch_dream",
    "build_agent_plasticity_lease",
    "build_independent_agent_cell",
    "build_physical_option_request",
    "build_team_coordination_frame",
    "build_failure_conditioned_dreams",
    "evaluate_alternating_growth",
    "evaluate_alternating_growth_round",
    "evaluate_joint_growth",
    "evaluate_joint_growth_round",
    "evaluate_first_touch",
    "evaluate_paired_champion",
    "fit_dynamic_lead_pass_policy",
    "fit_two_vs_one_tactical_actor",
    "decision_payload",
    "default_three_role_search_spaces",
    "build_g1_mosaic_gmt_overhead_skill",
    "build_g1_mosaic_gmt_getup_skill",
    "learn_joint_policy_generation",
    "load_g1_mosaic_gmt_overhead_skill",
    "load_g1_mosaic_gmt_getup_skill",
    "load_mjlab_getup_torch",
    "load_mosaic_gmt_torch",
    "load_two_vs_one_tactical_actor",
    "prioritize_team_curriculum",
    "reconstruct_s33_champion_registry",
    "save_two_vs_one_tactical_actor",
    "write_s33_champion_registry",
]
